site_name: "There and Bark Again: A Corgi's Journey Into Python"
site_url: "https://mathewrupp.github.io/taba"
theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: "index.md"
  - "Chapter 1: An Unexpected Journey":
      - "Why Python": "whypython.md"
      - "Installing Python": "installation.md"
  - About: "about.md"
